-- 50 tarefas de mineração (você pode executar no banco)
DELETE FROM mining_tasks;
INSERT INTO mining_tasks (name, description, daily_limit, reward_amount, is_active) VALUES
('Adele - Rolling in the Deep', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Ed Sheeran - Shape of You', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Taylor Swift - Blank Space', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Wheels On The Bus', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Michael Jackson - Beat It', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Shawn Mendes - Señorita', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Alan Walker - Faded', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Bruno Mars - The Lazy Song', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Katy Perry - Roar', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Chilled Serenity #5', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Mineração Bronze', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Mineração Prata', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Mineração Ouro', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Eminem - Love The Way You Lie', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Ed Sheeran - Perfect', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Queen - Bohemian Rhapsody', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Numb - Linkin Park', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Shakira - Waka Waka', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Learn Python - Full Course', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Me at the zoo', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Luis Fonsi - Despacito', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Mark Ronson - Uptown Funk', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Smash Mouth - All Star', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Adele - Hello', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Ricky Martin - Livin La Vida Loca', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Beyoncé - Halo', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Justin Bieber - Sorry', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Coldplay - Viva La Vida', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('The Weeknd - Blinding Lights', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Dua Lipa - Don''t Start Now', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Harry Styles - Watermelon Sugar', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Billie Eilish - Bad Guy', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Post Malone - Sunflower', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Ozuna - Sincero', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('J Balvin - Mi Gente', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Maluma - Hawái', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Anitta - Envolva', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Luan Santana - Maldoc', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Jorge e Mateus - Desça', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Zé Neto - Freio de Combustão', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Matheus Battisti - Corrente', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('MC Poze do Rodo - Sozinha', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Haikaiss - RAP Lord', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('Xamã - Cravo e a Rosa', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Belo - Traidor', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Clayton e Bambolú - Pede pra Sair', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Teto - Monalisa', 'Mineração intermediária com retorno estável.', 10, 0.50, 1),
('WIU - Sindérese', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Sidoka - Atchim', 'Mineração avançada com maior recompensa.', 10, 0.50, 1),
('Borges - Eh Claudinho', 'Execute mineração básica com baixo consumo.', 10, 0.50, 1),
('Teto - Vou Não', 'Mineração intermediária com retorno estável.', 10, 0.50, 1);
